-- Supabase Database Schema for Telegram AI Bot Memory
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster filtering by user_id
CREATE INDEX IF NOT EXISTS idx_memories_user_id ON public.memories(user_id);

CREATE TABLE IF NOT EXISTS public.study_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan_details TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_plans_user_id ON public.study_plans(user_id);

-- Optional: Enable Row Level Security (RLS) if you plan to expose the DB to a frontend later
-- ALTER TABLE public.memories ENABLE ROW LEVEL SECURITY;
