-- Exécutez ce script dans le SQL Editor de Supabase pour le système de Planning

-- 1. Table des Examens / Objectifs principaux
CREATE TABLE IF NOT EXISTS public.exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    subject TEXT NOT NULL,
    exam_date DATE NOT NULL,
    goal_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table des Sessions de Révision (associées à un examen)
CREATE TABLE IF NOT EXISTS public.revision_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES public.exams(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    planned_date DATE NOT NULL,
    topic TEXT NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    notified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Index pour optimiser les requêtes du bot (vérification des rappels quotidiens)
CREATE INDEX IF NOT EXISTS idx_exams_user ON public.exams(user_id);
CREATE INDEX IF NOT EXISTS idx_revision_sessions_user_date ON public.revision_sessions(user_id, planned_date);
CREATE INDEX IF NOT EXISTS idx_revision_sessions_notified ON public.revision_sessions(notified, planned_date);
