-- Exécutez ce script dans le SQL Editor de Supabase

-- 1. Création de la table pour stocker les textes extraits des photos de cours
CREATE TABLE IF NOT EXISTS public.course_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tag TEXT NOT NULL,
    extracted_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Index pour accélérer les recherches par utilisateur et par tag
CREATE INDEX IF NOT EXISTS idx_course_materials_user_tag ON public.course_materials(user_id, tag);

-- (Optionnel) Vous pouvez également créer un bucket "course_photos" manuellement dans Supabase Storage
-- si vous souhaitez à l'avenir conserver les images originales. Pour l'instant, seul le texte est requis.
