services:
  - type: web
    name: bot-ia-telegram
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OLLAMA_API_KEY
        sync: false
      - key: OLLAMA_API_URL
        value: https://ollama.com/v1
      - key: OLLAMA_MODEL
        value: minimax-m2.5:cloud
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: ALLOWED_USERS
        value: "5981844665"
